### ISSUE TITLE
internal/docker - angular fails to work

### ISSUE THREAD

**Issue by MajoBerger** [dataquest-dev/dspace-angular#190]
This behaviour is consistent but unexplained. Only observed on my machine so far, but I did not manage to
resolve or identify it.

![image](https://github.com/dataquest-dev/dspace-angular/assets/88670521/35eca132-9bc8-42eb-83da-a6b293f43eae)

**Comment by milanmajchrak** [comment]
It's been fixed in the customization for TUL customer.
