### ISSUE TITLE
internal/import data to dev-5

### ISSUE THREAD

**Issue by MajoBerger** [dataquest-dev/dspace-angular#194]

**Comment by MajoBerger** [comment]
Waiting for review from Milan Majchrak, if procedure is understandable.
Added action in dspace-angular repo = erase database and added extract_data to python api. 
Usage [described in wiki](https://github.com/dataquest-dev/DSpace/wiki/Developing-dev5#importing-data-to-dev-5)

**Comment by milanmajchrak** [comment]
@MajoBerger  I've try it and is' working.
