### ISSUE TITLE
TUL/after hover on button strange lines are seen

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-angular#202]
## Problem description
Do you see this strange lines after hover event on the button? 
![image](https://github.com/dataquest-dev/dspace-angular/assets/90026355/b87df40c-2e3a-4823-a045-acb85afb92ff)

https://github.com/dataquest-dev/dspace-angular/assets/90026355/4067981d-449b-4b85-aaf2-9a44a78a24df

Please fix this strange behavior.

**Comment by HuynhKhoa1601** [comment]
It does not appear on my site. But let me try to replicate it.

**Comment by milanmajchrak** [comment]
> Collaborator

What browser do you have? I use Google Chrome

**Comment by HuynhKhoa1601** [comment]
I use both Microsoft Edge and Google Chrome but still cannot see
