### ISSUE TITLE
internal/problem with docker cli (to issue dspace commands

### ISSUE THREAD

**Issue by MajoBerger** [dataquest-dev/dspace-angular#207]

**Comment by milanmajchrak** [comment]
## Problem description
The user cannot create an admin by using docker/cli.yml. DSpace throws an error which tells you nothing why it's not working.
Example of the command which is not working: `docker-compose --env-file .env -p dq-d7 -f docker/cli.yml run --rm dspace-cli create-administrator -e <EMAIL> -f admin -l user -p <ADMIN> -c en -o dataquest`
