### ISSUE TITLE
internal/configure host for S3

### ISSUE THREAD

**Issue by MajoBerger** [dataquest-dev/dspace-angular#242]
Required to be able to use Cesnet S3 repository

**Comment by milanmajchrak** [comment]
@MajoBerger Could it be closed? Where it was developed?

**Comment by MajoBerger** [comment]
@milanmajchrak there is guide in our Teams on how to use it.
It was developed in BE here https://github.com/dataquest-dev/DSpace/pull/338

Is this information sufficient to close this issue?
