### ISSUE TITLE
internal/fixing-deploy

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-angular#31]
Update deploy to:
diff --git a/build-scripts/deploy-scripts/deploy.yml b/build-scripts/deploy-scripts/deploy.yml
index fadb4d7..0476027 100644
--- a/build-scripts/deploy-scripts/deploy.yml
+++ b/build-scripts/deploy-scripts/deploy.yml
@@ -24,7 +24,7 @@ services:
       DSPACE_UI_PORT: '4000'
       DSPACE_UI_NAMESPACE: /
       DSPACE_REST_SSL: 'false'
-      DSPACE_REST_HOST: localhost
+      DSPACE_REST_HOST: dev-5.pc
       DSPACE_REST_PORT: 8080
       DSPACE_REST_NAMESPACE: /server
     image: dataquest/dspace-angular:dspace-7_x
@@ -48,8 +48,8 @@ services:
       # __D__ => "-" (e.g. google__D__metadata => google-metadata)
       # dspace.dir, dspace.server.url, dspace.ui.url and dspace.name
       dspace__P__dir: /dspace
-      dspace__P__server__P__url: http://localhost:8080/server
-      dspace__P__ui__P__url: http://localhost:4000/
+      dspace__P__server__P__url: http://dev-5.pc:8080/server
+      dspace__P__ui__P__url: http://dev-5.pc/
       dspace__P__name: 'DSpace Started with Docker Compose'
       # db.url: Ensure we are using the 'dspacedb' image for our database
       db__P__url: 'jdbc:postgresql://dspacedb:5432/dspace'

- add admin account

**Comment by vidiecan** [comment]
closing as this one is fixed, follow up in #47
