### ISSUE TITLE
Tag images in docker hub

### ISSUE THREAD

**Issue by MajoBerger** [dataquest-dev/dspace-angular#333]

**Comment by MajoBerger** [comment]
We can manually tag images according to this
https://docs.docker.com/docker-hub/repos/
@milanmajchrak do you think this is sufficient?

**Comment by milanmajchrak** [comment]
> We can manually tag images according to this https://docs.docker.com/docker-hub/repos/ @milanmajchrak do you think this is sufficient?

Yeah, that's great. Thank you.

**Comment by MajoBerger** [comment]
will do that with next (and every following) release

**Comment by MajoBerger** [comment]
Done in TUL for the first time, info in dspace-customers.
