### ISSUE TITLE
Login banner popping  up too much

### ISSUE THREAD

**Issue by MajoBerger** [dataquest-dev/dspace-angular#365]
E.g. on http://dev-5.pc:85/login login banner on the right:
![image](https://github.com/dataquest-dev/dspace-angular/assets/88670521/2e83d48a-5f0b-482a-808b-797cc3af1c0b)
pops up each time browser lands on /login, even when redirected from that banner. Even when wrong credentials are supplied, banner appears again. It IS annoying.

**Comment by milanmajchrak** [comment]
2024/01:roadmap: should be fixed
