### ISSUE TITLE
Deploy UK issue

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-angular#403]
## Problem description
Describe steps how to deploy a new DSpace docker image on the server.

**Requirements:**
- docker compose v2 (`docker compose version`)
- If you need to set up `namespace` e.g. `/repository` do not forget update it in the `aai.js`

**Steps need to be done:**
@MajoBerger 

**Info 4y:**  @MajoBerger 
- BE/FE docker image from the dockerhub. BE: `dataquest/dspace:customer-uk` FE: `dataquest/dspace-angular:customer-uk`
- Set up docker envs
- Check actions
- prod configs
- Running UK test environment: https://dspace-dev.ufal.mff.cuni.cz/home
- Running dev5-UK ...: http://dev-5.pc:82

**Branches:**
BE: https://github.com/dataquest-dev/DSpace/tree/customer/uk
FE: https://github.com/dataquest-dev/dspace-angular/tree/customer/uk

**Comment by MajoBerger** [comment]
Installation guide:
https://github.com/dataquest-dev/DSpace/wiki/Installation#running-dspace-in-docker
