### ISSUE TITLE
Missing info in License Agreement after login as user

### ISSUE THREAD

**Issue by Paurikova2** [dataquest-dev/dspace-angular#413]
I tried to download restricted bitstream as anonymous user. I was redirected to login page. I logged in as User by [milan.majchrak1@gmail.com](mailto:milan.majchrak1@gmail.com) and I got this result. There are missing information in some fields.

![Image](https://github.com/dataquest-dev/dspace-angular/assets/107862249/2513636f-24e0-4c21-a78e-acc578a72b33)

**Comment by milanmajchrak** [comment]
Fixed here: https://github.com/dataquest-dev/dspace-angular/issues/419
