### ISSUE TITLE
Uncorrected page after trying download restricted bitstream by local login

### ISSUE THREAD

**Issue by Paurikova2** [dataquest-dev/dspace-angular#414]
I tried to download restricted bitstream as anonymous user. I was redirected to login page. I logged as Admin by [milan.majchrak@gmail.com](mailto:milan.majchrak@gmail.com). The file was successfully downloaded, but the page forze.

![Image](https://github.com/dataquest-dev/dspace-angular/assets/107862249/251f17a4-4c77-4d2f-bd1c-d7768816917e)

After refreshing: (I was already logged in). But when I chose some option from bar menu, it worked and website has started to be normal.

![Image](https://github.com/dataquest-dev/dspace-angular/assets/107862249/090d5aa0-0413-4b06-8f4f-1e43865386a0)

**Comment by milanmajchrak** [comment]
Fixed here: https://github.com/dataquest-dev/dspace-angular/issues/422
