### ISSUE TITLE
Access item in restricted collection

### ISSUE THREAD

**Issue by Paurikova2** [dataquest-dev/dspace-angular#418]
1. I created new person by `Access Control` -> `Person`
2. I created new collection. In mark `Assign Roles` -> `Default item read access` and `Default bitstream read access` I pushed the buttons `Restrict`. In mark `Authorization I added new authorization for created person.
3. In `Access Control` -> `Person` I added created person to group `COLLECTION_[created collection uuid]_ITEM_DEFAULT_READ.
4. I created item in this collection with public available license.

Result: When you are log in as person, whose is not member of ITEM_DEFAULT_READ group and the items have public available license and these items **were created after added restricted use for collection**, you cannot see these items. **RIGHT**
![Image](https://github.com/dataquest-dev/dspace-angular/assets/107862249/203e9da3-5518-4f3b-b90c-3302ae4832f4)

Result: When you create items in collection and **after that you will add restricted use for collection**, you will see these items without collection despite that you shouldn't have policies! **ERROR**

![Image](https://github.com/dataquest-dev/dspace-angular/assets/107862249/0f8a8d3d-749e-41a1-b03d-3dc4e7a9db5d)

Result: When you are  member of ITEM_DEFAULT_READ group, but you are **not assigned in collection `Authorization`**, you can see  items but without collection. (Items were created **after added restricted use for collection**) **ERROR?**
 
![Image](https://github.com/dataquest-dev/dspace-angular/assets/107862249/c17ec8d2-f3b5-4a8b-b6b0-f7d5ec60dcca)

Result: When you follow the descripted steps and you are log in, you can see items with collection. (But you don't see items created before added restricted use) **RIGHT?**

![Image](https://github.com/dataquest-dev/dspace-angular/assets/107862249/203e9da3-5518-4f3b-b90c-3302ae4832f4)

**Comment by MajoBerger** [comment]
moved into known issues
