### ISSUE TITLE
Fix License contract page (Distribution license)

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-angular#510]
1. The user is redirected to the `http://dev-5.pc:85/contract%3FcollectionId%3D4210035f-a6c0-4255-8e88-c3a2490700c0` instead of `http://dev-5.pc:85/contract?collectionId=4210035f-a6c0-4255-8e88-c3a2490700c0`
2. Distribution license is not translated
**Excel Notes:** license.alternative.path: it is for translating the distribution license. Distribution license is defined in the collection but still in the same language. Update loading the collection license - it will be loaded from some static file like in the CLARIN.

5/Apr/2024 - OK:
```
trik je https://github.com/ufal/clarin-dspace/commit/06dac68f6c2eb5fcdada1c46e46ee10710966b1c#diff-06a9b3a5cc54ccb1654abfdc343ef91cd1c4ef8e6e537494e999aa78de62141cR166 - license url se pouzije jako klic, a pokud danej klic v katalogu (mezi prekladama) neni, pouzije (skoro) prazdnej retezec s mezerou - zbytek toho commitu je presvedcovani dspacu, aby to proslo
tady je ceskej text licence: https://github.com/ufal/clarin-dspace/commit/55acf1252e033c3292b524f9e277869cdc5de166#diff-7038a53c9d4b03300c3bff8b4aca10946dfcf1bd84e588586bc36b8884b23824R3310
staticka stranka bere text taky z prekladovyho katalogu: https://github.com/ufal/clarin-dspace/commit/55acf1252e033c3292b524f9e277869cdc5de166#diff-2efd5de166b8f91e3934f42a1f6a7c42c72870d1cae62c6f25df52fc0be1ff5aR3
anglickej preklad je pridanej az v https://github.com/ufal/clarin-dspace/commit/a68f67d8a602c6262b976e94ebfa83df1ca2fd2a
```

1/May/2024:

1. PR: https://github.com/dataquest-dev/dspace-angular/pull/613

2.1.: Add czech translation for the distrubution license
2.2. OK's comment from 5/Apr/2024 is talking about a new license static page and what? Where is loaded that message? V7 does not use messages than v5 - we need to implement that differently.

2/May/2024:
- Item with name `MLASK`
- License info: The text is loaded from message
- Download restricted Item: The same info as in the /license page is showed above the download button

![Image](https://github.com/dataquest-dev/dspace-angular/assets/90026355/ec3cf36b-c121-45e7-b6e8-6c11590eaa05)

**Comment by kosarko** [comment]
`ufal-showstopper` kvuli te licenci pro mlask dataset. Kde musime text ukazat v miste kde je tlacitko "agree" (nesmi byt za odkazem). Text licence je lokalizovany (en, cs). klidne muze byt v `{en,cs}.json5`

---

mene akutni:

1. 
>1. The user is redirected to the ...

to uz je fixnute? mam pocit, ze ze submission me to redirectlo spravne.

2.  /contract neni ve vanille? A bere to bud default licenci, nebo tu z collection metadat?

**Comment by milanmajchrak** [comment]
1. Nedokazem zreplikovat, pravdepodobne je to fixnute, ked som opravoval encoding parametrov v celom DSpace.
2. Issue: https://github.com/dataquest-dev/dspace-angular/issues/723
3. MLASK - done here: https://github.com/dataquest-dev/dspace-angular/pull/722

**Comment by milanmajchrak** [comment]
@kosarko 
2. `/contract` neni vo vanille, to sme dorabali my. Berie to licenciu z collection metadata a tam to nie je prelozene.

**Comment by kosarko** [comment]
@milanmajchrak ta szn licence se chova nejak divne...nacita ji to dokola a dokola

https://github.com/user-attachments/assets/d657f937-0588-4c80-b79d-9c4ec7771fed
