### ISSUE TITLE
Update all static licenses

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-angular#589]
1. Compare all license files
2. Check commits from the 2022 - now and update license files: https://github.com/ufal/clarin-dspace/commits/clarin/dspace-xmlui/src/main/webapp/themes/UFAL/lib/html

**Comment by kosarko** [comment]
`ufal-showstopper`

1. Pri prechodu na produkci potrebujeme mit v databazi minimalne vsechny pouzite licence (to predpokladam zaridi pumpa)
2. u custom licenci (ty ktere maji ve v5 static page) potrebujeme prenest content (ty static pages)
3. pokud static content linkuje nekam v ramci repozitare (zejmena /xmlui/ je potreba to zaktualizovat)
4. update `dc.rights.uri`

xxx
2.  a 3. asi muze udelat @kosarko, pokud bude vedet jak.
4. teoreticky taky, pokud je potreba jen cisty metadata update na itemech. ale ono asi bude potreba nejak aktualizovat i license definition (a nevim, jestli to tim konci)...

**Comment by milanmajchrak** [comment]
1. Ano, pumpa ich zmigruje
2. TODO - nejake tam su, ale treba ich aktualizovat
3. TODO - Tie static licenses, ktore tam su by mali mat zmenemu path, aby tam nebolo `xmlui`, pri novych to treba updatnut
4. Myslim, ze pumpa toto zariadi, len treba nastavit: https://github.com/dataquest-dev/dspace-import/blob/main/src/project_settings.py#L59

**Comment by milanmajchrak** [comment]
- All static licensese from this: [license-ud-2.14](https://lindat.mff.cuni.cz/repository/xmlui/page/license-ud-2.14) copy to this: https://github.com/dataquest-dev/dspace-angular/tree/dtq-dev/src/static-files 
- You can see static pages in the v7 like this: https://dev-5.pc:8443/static/about

NOTE:
- Copy only html, ignore xml
- Do not forget to copy cs translation, add it to https://github.com/dataquest-dev/dspace-angular/tree/dtq-dev/src/static-files/cs
- Go through all licenses and check hardcoded urls
