### ISSUE TITLE
frontend can't be deployed on subpath

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-angular#610]
Original issue: https://github.com/ufal/clarin-dspace/issues/1027

**Comment by kosarko** [comment]
`ufal-showstopper` see the last paragraph in https://github.com/ufal/clarin-dspace/issues/1027#issuecomment-2405021733

**Comment by milanmajchrak** [comment]
Slack question:
```
Hi all, I'm struggling to change the DSPACE_REST_NAMESPACE for the server when starting DSpace via Docker. When I modify the DSPACE_REST_NAMESPACE property to DSPACE_REST_NAMESPACE=/repository/server, the backend (BE) still runs on localhost:8080/server instead of localhost:8080/repository/server. However, the BE configuration property dspace.server is updated to localhost:8080/repository/server.
Despite the configuration change, the backend continues running on the old path. When I check the running backend, it looks like this:
Do you know an easy way to change the REST namespace when running DSpace via Docker?
```
![Image](https://github.com/user-attachments/assets/56dca5e5-a881-4c15-8eaa-76c91139550e)

**Comment by milanmajchrak** [comment]
I would like to update the Dockerfile to get namespace from the `.env`. https://github.com/dataquest-dev/DSpace/blob/dtq-dev/Dockerfile#L63

Technical talk needed

**Comment by milanmajchrak** [comment]
> Slack question:
> 
> ```
> Hi all, I'm struggling to change the DSPACE_REST_NAMESPACE for the server when starting DSpace via Docker. When I modify the DSPACE_REST_NAMESPACE property to DSPACE_REST_NAMESPACE=/repository/server, the backend (BE) still runs on localhost:8080/server instead of localhost:8080/repository/server. However, the BE configuration property dspace.server is updated to localhost:8080/repository/server.
> Despite the configuration change, the backend continues running on the old path. When I check the running backend, it looks like this:
> Do you know an easy way to change the REST namespace when running DSpace via Docker?
> ```
> 
> ![Image](https://github.com/user-attachments/assets/56dca5e5-a881-4c15-8eaa-76c91139550e)

The issue is that the `Referer` in the UI request does not include the `/repository/` namespace. Due to the `Referrer Policy: strict-origin-when-cross-origin`, the UI request ignores the namespace if the UI and backend have different URLs (i.e., different ports).

So when the UI and BE has the same URL (origin) everything will work correctly.

**Comment by milanmajchrak** [comment]
https://github.com/dataquest-dev/dspace-angular/pull/730

**Comment by milanmajchrak** [comment]
I've written down the steps how to set up `namespace` properly: https://github.com/dataquest-dev/DSpace/wiki/Custom-namespace

**Comment by milanmajchrak** [comment]
TODO: think how to change `assets` file paths when `namespace` is set.

**Comment by milanmajchrak** [comment]
Images without namespace:
- from discojuice.js
- dariah-eu.png
- clarin.png
- images/mime/
