### ISSUE TITLE
internal/change-test-data-for-frontend

### ISSUE THREAD

**Issue by MajoBerger** [dataquest-dev/dspace-angular#80]
We need specific data for testing frontend. We need to be able to customise them in the future.
@milanmajchrak specify which data we need to add now

Hints we've found so far.
these data are used: https://github.com/DSpace-Labs/AIP-Files/releases/download/demo-entities-data/dspace7-entities-2021-04-14.sql
loaded here: https://github.com/dataquest-dev/dspace-angular/blob/dtq-dev/docker/docker-compose-ci.yml#L66
short description: https://github.com/DSpace-Labs/AIP-Files/releases/tag/demo-entities-data

[Our wiki instructions for database import and export](https://github.com/dataquest-dev/DSpace/wiki/Developing-backend#database-dumps-and-migrations).

**Comment by MajoBerger** [comment]
We need to add file with .sql dump somewhere. Options so far:
- ~~upload to dev-5~~ - it won't run on dev-5
- make a release on github and download it as it is done now (but publish our own release with .sql dump)
![image](https://user-images.githubusercontent.com/88670521/184345732-e3312c24-a1d2-48b2-bea3-e11ad49ce138.png)
- upload it elsewhere..? but would that be safe or necessary?

**Comment by milanmajchrak** [comment]
How to create database dump: https://github.com/dataquest-dev/DSpace/wiki/CLI-commands#create-database-dump
